bumped c8y/client ngx-components and styles version to latest published
SoftwareAG/cumulocity-community-plugins pull request #21
Opened 2023-11-17 12:55 UTC by eniosultan

Bumped ngx/components client and styles version to latest published one in order to fix issue with asset selector icons not being displayed. Additionally the plugin should now share the same package instances in the cumulocity platform instead of using a separate one.

2023-11-17 13:08 UTC, jdreSAG requested changes

2023-11-17 13:08 UTC, jdreSAG commented on package.json
> +  "version": "2.1.6",
version will be bumped automatically, revert this change

2023-11-17 13:42 UTC, reey commented on package-lock.json
there are way to many changes in this file from my point of view..

2023-11-17 13:43 UTC, reey commented on package.json
`@c8y/cli` was missed..

2023-11-17 15:04 UTC, eniosultan commented on package.json
added

2023-11-17 15:12 UTC, eniosultan commented on package-lock.json
reverted

2023-11-20 07:51 UTC, eniosultan commented
> please also add a little bit more description in PR description- what was exact issue, what was causing it (not sharing ngx-components between plugin and shell). In 1 month we will forget what was the issue and this repo has no link with our internal JIRA

done

2023-11-20 08:37 UTC, janhommes approved these changes

2023-11-27 09:19 UTC, merged